# Generated by Django 5.2.15 on 2026-07-06 21:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kitchen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=150)),
                ('manager', models.CharField(default='Not Assigned', max_length=100)),
                ('status', models.CharField(default='Active', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('stock_quantity', models.IntegerField()),
                ('minimum_stock', models.IntegerField(default=10)),
                ('supplier', models.CharField(max_length=100)),
                ('kitchen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kitchen.kitchen')),
            ],
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(default='General', max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('available', models.BooleanField(default=True)),
                ('kitchen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kitchen.kitchen')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(default='Walk-in Customer', max_length=100)),
                ('item_name', models.CharField(default='Unknown Item', max_length=100)),
                ('quantity', models.IntegerField(default=1)),
                ('status', models.CharField(default='Pending', max_length=30)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('order_date', models.DateField(auto_now_add=True)),
                ('kitchen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kitchen.kitchen')),
            ],
        ),
    ]
